project_id = "idnjdznpzjqhfjfetbdy"

[functions.get_available_slots]
verify_jwt = false

[functions.book_slot]
verify_jwt = false

[functions.cancel_booking]
verify_jwt = false

[functions.reschedule_booking]
verify_jwt = false